### PR TITLE
Updated-CSS

### PR DESCRIPTION
**Pull request by srvjha**
Added New Colour Combination to enhance the website.

### CODE REVIEW

**Comment by rachitag112** [comment]
Hey @srv269 @srvjha,
Please also deploy it on your repo so that we can check it and then merge it.

**Comment by srvjha** [comment]
Deployed The Repository With the name Website_Updated
Here is the link you can checkout:- https://github.com/srvjha/Website_Updated

**Comment by srvjha** [comment]
Deployed

**Comment by rachitag112** [comment]
@srvjha 
By deploy, I mean on GitHub Pages

**Comment by srv269** [comment]
Ok sorry for that, will do it now.

**Comment by rachitag112** [comment]
@srvjha 
The color is not looking good on the website, please consider changing it or try something new.
I'm closing this PR, please open new PR for the new changes.

Thanks

**Comment by srv269** [comment]
Ok

**Pull request closed without merging**
