### PR TITLE
Adding Core Team Section By Introducing It By Glassmorphism UI Trend

### PR DESCRIPTION
**Pull request by KunalUpadhyay02**
[Live Demo Of Changes💻](https://kunalupadhyay02.github.io/hackclubwebsite/core.html)

### CODE REVIEW

**Comment by rachitag112** [comment]
@KunalUpadhyay02 
Please remove the background and the outer box
Just add the person floating boxes and also fix the dimensions

**Comment by KunalUpadhyay02** [comment]
[Live Demo of Changes](https://kunalupadhyay02.github.io/hackclubwebsite/core.html)

**Review by adityavijay21 — CHANGES_REQUESTED** [review]
LGTM💯

**Comment by rachitag112** [comment]
Great work!

Thanks for contributing

**Pull request merged**
